In [6]:
!pip install --user sweetviz

/usr/local/anaconda/lib/python3.7/site-packages/secretstorage/dhcrypto.py:16: CryptographyDeprecationWarning: int_from_bytes is deprecated, use int.from_bytes instead
  from cryptography.utils import int_from_bytes
/usr/local/anaconda/lib/python3.7/site-packages/secretstorage/util.py:25: CryptographyDeprecationWarning: int_from_bytes is deprecated, use int.from_bytes instead
  from cryptography.utils import int_from_bytes
Requirement already satisfied: sweetviz in /home/ubuntu/.local/lib/python3.7/site-packages (2.1.3)
Requirement already satisfied: matplotlib>=3.1.3 in /home/ubuntu/.local/lib/python3.7/site-packages (from sweetviz) (3.4.3)
Requirement already satisfied: scipy>=1.3.2 in /home/ubuntu/.local/lib/python3.7/site-packages (from sweetviz) (1.7.1)
Requirement already satisfied: tqdm>=4.43.0 in /usr/local/anaconda/lib/python3.7/site-packages (from sweetviz) (4.61.2)
Requirement already satisfied: importlib-resources>=1.2.0 in /home/ubuntu/.local/lib/python3.7/site-packages (from sweetviz) (5.3.0)
Requirement already satisfied: jinja2>=2.11.1 in /home/ubuntu/.local/lib/python3.7/site-packages (from sweetviz) (3.0.2)
Requirement already satisfied: numpy>=1.16.0 in /home/ubuntu/.local/lib/python3.7/site-packages (from sweetviz) (1.21.3)
Requirement already satisfied: pandas!=1.0.0,!=1.0.1,!=1.0.2,>=0.25.3 in /home/ubuntu/.local/lib/python3.7/site-packages (from sweetviz) (1.3.4)
Requirement already satisfied: zipp>=3.1.0 in /home/ubuntu/.local/lib/python3.7/site-packages (from importlib-resources>=1.2.0->sweetviz) (3.6.0)
Requirement already satisfied: MarkupSafe>=2.0 in /home/ubuntu/.local/lib/python3.7/site-packages (from jinja2>=2.11.1->sweetviz) (2.0.1)
Requirement already satisfied: pillow>=6.2.0 in /home/ubuntu/.local/lib/python3.7/site-packages (from matplotlib>=3.1.3->sweetviz) (8.4.0)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/anaconda/lib/python3.7/site-packages (from matplotlib>=3.1.3->sweetviz) (2.8.0)
Requirement already satisfied: kiwisolver>=1.0.1 in /usr/local/anaconda/lib/python3.7/site-packages (from matplotlib>=3.1.3->sweetviz) (1.0.1)
Requirement already satisfied: cycler>=0.10 in /usr/local/anaconda/lib/python3.7/site-packages (from matplotlib>=3.1.3->sweetviz) (0.10.0)
Requirement already satisfied: pyparsing>=2.2.1 in /usr/local/anaconda/lib/python3.7/site-packages (from matplotlib>=3.1.3->sweetviz) (2.3.1)
Requirement already satisfied: six in /usr/local/anaconda/lib/python3.7/site-packages (from cycler>=0.10->matplotlib>=3.1.3->sweetviz) (1.12.0)
Requirement already satisfied: setuptools in /usr/local/anaconda/lib/python3.7/site-packages (from kiwisolver>=1.0.1->matplotlib>=3.1.3->sweetviz) (52.0.0.post20210125)
Requirement already satisfied: pytz>=2017.3 in /usr/local/anaconda/lib/python3.7/site-packages (from pandas!=1.0.0,!=1.0.1,!=1.0.2,>=0.25.3->sweetviz) (2018.9)

In [1]:
import sweetviz as sv
import pandas as pd
import numpy as np

/home/ubuntu/.local/lib/python3.7/site-packages/pandas/compat/_optional.py:138: UserWarning: Pandas requires version '2.7.0' or newer of 'numexpr' (version '2.6.9' currently installed).
  warnings.warn(msg, UserWarning)

In [6]:
!pip install --user pandas==3.0.0

/usr/local/anaconda/lib/python3.7/site-packages/secretstorage/dhcrypto.py:16: CryptographyDeprecationWarning: int_from_bytes is deprecated, use int.from_bytes instead
  from cryptography.utils import int_from_bytes
/usr/local/anaconda/lib/python3.7/site-packages/secretstorage/util.py:25: CryptographyDeprecationWarning: int_from_bytes is deprecated, use int.from_bytes instead
  from cryptography.utils import int_from_bytes
ERROR: Could not find a version that satisfies the requirement pandas==3.0.0 (from versions: 0.1, 0.2, 0.3.0, 0.4.0, 0.4.1, 0.4.2, 0.4.3, 0.5.0, 0.6.0, 0.6.1, 0.7.0, 0.7.1, 0.7.2, 0.7.3, 0.8.0, 0.8.1, 0.9.0, 0.9.1, 0.10.0, 0.10.1, 0.11.0, 0.12.0, 0.13.0, 0.13.1, 0.14.0, 0.14.1, 0.15.0, 0.15.1, 0.15.2, 0.16.0, 0.16.1, 0.16.2, 0.17.0, 0.17.1, 0.18.0, 0.18.1, 0.19.0, 0.19.1, 0.19.2, 0.20.0, 0.20.1, 0.20.2, 0.20.3, 0.21.0, 0.21.1, 0.22.0, 0.23.0, 0.23.1, 0.23.2, 0.23.3, 0.23.4, 0.24.0, 0.24.1, 0.24.2, 0.25.0, 0.25.1, 0.25.2, 0.25.3, 1.0.0, 1.0.1, 1.0.2, 1.0.3, 1.0.4, 1.0.5, 1.1.0, 1.1.1, 1.1.2, 1.1.3, 1.1.4, 1.1.5, 1.2.0, 1.2.1, 1.2.2, 1.2.3, 1.2.4, 1.2.5, 1.3.0, 1.3.1, 1.3.2, 1.3.3, 1.3.4)
ERROR: No matching distribution found for pandas==3.0.0

In [19]:
df1 = pd.read_csv("Lettuce priming - VR and TT.csv")
df1

,Unnamed: 0,Process analysis details,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 69,Unnamed: 70,Unnamed: 71,Unnamed: 72,Unnamed: 73,Unnamed: 74,Unnamed: 75,Unnamed: 76,Unnamed: 77,Unnamed: 78
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Priming Time (Hr),Supply Team,MG,MG Desc,MPG,MCT,SCO,Phase,Basic Material w/o Leading Zeros,Basic Variety Name,...,UT: % Abnormals,UT: % Ungerminated seeds,NaN,NaN,VR: Vigor Rating,TT: % Normal seedlings 24C,TT: % Normal seedlings 28C,VR: Vigor Rating,TT: % Normal seedlings 24C,TT: % Normal seedlings 28C
3,36,LEAFY,H187,LETTUCE,T4,BAV,OPN,5C,10822519,VENEGIA,...,NaN,NaN,NaN,NaN,10,100,42.5,0,100,99.5
4,28,LEAFY,H187,LETTUCE,T4,BUT,OPN,5C,10776016,TOUAREG,...,NaN,NaN,NaN,NaN,9.3125,90.5,74,0,100,100
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1511,48,LEAFY,H187,LETTUCE,T4,CHD,OPN,5B,10811570,MOHAWK,...,NaN,NaN,NaN,NaN,0,67,1.5,0,100,100
1512,48,LEAFY,H187,LETTUCE,T4,LOL,OPN,5C,10818377,XENON,...,NaN,NaN,NaN,NaN,0,97.5,55,0,100,99
1513,36,LEAFY,H187,LETTUCE,T4,FRI,OPN,5C,10806290,FRILLICE,...,NaN,NaN,NaN,NaN,0,98.5,18,0,100,99
1514,48,LEAFY,H187,LETTUCE,T4,BAV,OPN,5C,10759393,HUGIN,...,NaN,NaN,NaN,NaN,0,86,7.5,0,100,100
1515,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [20]:
df1.columns = df1.iloc[2]
df1 = df1.iloc[3:]
df1

2,Priming Time (Hr),Supply Team,MG,MG Desc,MPG,MCT,SCO,Phase,Basic Material w/o Leading Zeros,Basic Variety Name,...,UT: % Abnormals,UT: % Ungerminated seeds,NaN,NaN,VR: Vigor Rating,TT: % Normal seedlings 24C,TT: % Normal seedlings 28C,VR: Vigor Rating,TT: % Normal seedlings 24C,TT: % Normal seedlings 28C
3,36,LEAFY,H187,LETTUCE,T4,BAV,OPN,5C,10822519,VENEGIA,...,NaN,NaN,NaN,NaN,10,100,42.5,0,100,99.5
4,28,LEAFY,H187,LETTUCE,T4,BUT,OPN,5C,10776016,TOUAREG,...,NaN,NaN,NaN,NaN,9.3125,90.5,74,0,100,100
5,24,LEAFY,H187,LETTUCE,T4,FRI,OPN,5C,10806290,FRILLICE,...,NaN,NaN,NaN,NaN,9.9375,100,74.5,0,100,99.5
6,36,LEAFY,H187,LETTUCE,T4,BUT,OPN,5C,10776016,TOUAREG,...,NaN,NaN,NaN,NaN,9.9375,94.5,13,0,100,97.5
7,36,LEAFY,H187,LETTUCE,T4,CRC,OPN,6D,10904727,PS 6545691,...,NaN,NaN,NaN,NaN,9.03125,0,0,0,100,99.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1511,48,LEAFY,H187,LETTUCE,T4,CHD,OPN,5B,10811570,MOHAWK,...,NaN,NaN,NaN,NaN,0,67,1.5,0,100,100
1512,48,LEAFY,H187,LETTUCE,T4,LOL,OPN,5C,10818377,XENON,...,NaN,NaN,NaN,NaN,0,97.5,55,0,100,99
1513,36,LEAFY,H187,LETTUCE,T4,FRI,OPN,5C,10806290,FRILLICE,...,NaN,NaN,NaN,NaN,0,98.5,18,0,100,99
1514,48,LEAFY,H187,LETTUCE,T4,BAV,OPN,5C,10759393,HUGIN,...,NaN,NaN,NaN,NaN,0,86,7.5,0,100,100
1515,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [21]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1513 entries, 3 to 1515
Data columns (total 79 columns):
 #   Column                              Non-Null Count  Dtype
---  ------                              --------------  -----
 0   Priming Time (Hr)                   1512 non-null   object
 1   Supply Team                         1512 non-null   object
 2   MG                                  1512 non-null   object
 3   MG Desc                             1512 non-null   object
 4   MPG                                 1512 non-null   object
 5   MCT                                 1512 non-null   object
 6   SCO                                 1511 non-null   object
 7   Phase                               1512 non-null   object
 8   Basic Material w/o Leading Zeros    1512 non-null   object
 9   Basic Variety Name                  1512 non-null   object
 10  Material #                          1512 non-null   object
 11  Material Desc                       1512 non-null   object
 12  FROM Pack Type                      1512 non-null   object
 13  TO Pack Type                        1512 non-null   object
 14  FROM Prod Form                      1512 non-null   object
 15  TO Prod Form                        1512 non-null   object
 16  Proc Code                           1505 non-null   object
 17  Area                                1502 non-null   object
 18  Harv Seq                            530 non-null    object
 19  Harv Date                           1512 non-null   object
 20  Crop Year                           1502 non-null   object
 21  Process Order                       1512 non-null   object
 22  FPO Plant                           1502 non-null   object
 23  OPO Plant                           1512 non-null   object
 24  Order Type                          1512 non-null   object
 25  Blend Indicator                     1512 non-null   object
 26  Scheduler Code                      1512 non-null   object
 27  Scheduler Code Description          1512 non-null   object
 28  Order Description                   1512 non-null   object
 29  Resources                           1511 non-null   object
 30  FROM Batch                          1512 non-null   object
 31  TO Batch                            1512 non-null   object
 32  FROM Supply Level                   1510 non-null   object
 33  TO Supply Level                     1512 non-null   object
 34  FROM Proc Stage                     1510 non-null   object
 35  TO Proc Stage                       1512 non-null   object
 36  FROM Vendor Batch Number (LotNr)    1512 non-null   object
 37  TO Vendor Batch Number (LotNr)      1512 non-null   object
 38  Prim cd                             0 non-null      object
 39  Sani cd                             852 non-null    object
 40  Input TSW                           1505 non-null   object
 41  Output TSW                          1503 non-null   object
 42  Create Date                         1512 non-null   object
 43  GR date                             1512 non-null   object
 44  GI QTY                              1512 non-null   object
 45  GI UOM                              1508 non-null   object
 46  GR QTY                              1512 non-null   object
 47  GR UOM                              1512 non-null   object
 48  Blend/Split                         128 non-null    object
 49  Running Count of Batches            1512 non-null   object
 50  Unique Line for Input Analysis      1512 non-null   object
 51  Unique Line for Output Analysis     1512 non-null   object
 52  ABC                                 1512 non-null   object
 53  SG: % Normal seedlings - 1st count  5 non-null      object
 54  SG: % Normal seedlings -final       698 non-null    object
 55  UT - 1st choice                     1492 non-null   object
 56  UT - total                          1492 non-null   object
 57  nan                                 0 non-null      float64
 58  nan                                 0 non-null      float64
 59  UT: % Abnormals                     1492 non-null   object
 60  UT: % Ungerminated seeds            1492 non-null   object
 61  nan                                 0 non-null      float64
 62  nan                                 0 non-null      float64
 63  SG: % Normal seedlings - 1st count  0 non-null      object
 64  SG: % Normal seedlings -final       22 non-null     object
 65  UT - 1st choice                     239 non-null    object
 66  UT - total                          239 non-null    object
 67  nan                                 0 non-null      float64
 68  nan                                 0 non-null      float64
 69  UT: % Abnormals                     239 non-null    object
 70  UT: % Ungerminated seeds            239 non-null    object
 71  nan                                 0 non-null      float64
 72  nan                                 0 non-null      float64
 73  VR: Vigor Rating                    1512 non-null   object
 74  TT: % Normal seedlings 24C          1512 non-null   object
 75  TT: % Normal seedlings 28C          1512 non-null   object
 76  VR: Vigor Rating                    1512 non-null   object
 77  TT: % Normal seedlings 24C          1512 non-null   object
 78  TT: % Normal seedlings 28C          1512 non-null   object
dtypes: float64(8), object(71)
memory usage: 933.9+ KB

In [22]:
df1=df1.dropna(axis=1,how='all')
df1=df1.dropna(axis=0,how='all')
df1.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1512 entries, 3 to 1514
Data columns (total 69 columns):
 #   Column                              Non-Null Count  Dtype
---  ------                              --------------  -----
 0   Priming Time (Hr)                   1512 non-null   object
 1   Supply Team                         1512 non-null   object
 2   MG                                  1512 non-null   object
 3   MG Desc                             1512 non-null   object
 4   MPG                                 1512 non-null   object
 5   MCT                                 1512 non-null   object
 6   SCO                                 1511 non-null   object
 7   Phase                               1512 non-null   object
 8   Basic Material w/o Leading Zeros    1512 non-null   object
 9   Basic Variety Name                  1512 non-null   object
 10  Material #                          1512 non-null   object
 11  Material Desc                       1512 non-null   object
 12  FROM Pack Type                      1512 non-null   object
 13  TO Pack Type                        1512 non-null   object
 14  FROM Prod Form                      1512 non-null   object
 15  TO Prod Form                        1512 non-null   object
 16  Proc Code                           1505 non-null   object
 17  Area                                1502 non-null   object
 18  Harv Seq                            530 non-null    object
 19  Harv Date                           1512 non-null   object
 20  Crop Year                           1502 non-null   object
 21  Process Order                       1512 non-null   object
 22  FPO Plant                           1502 non-null   object
 23  OPO Plant                           1512 non-null   object
 24  Order Type                          1512 non-null   object
 25  Blend Indicator                     1512 non-null   object
 26  Scheduler Code                      1512 non-null   object
 27  Scheduler Code Description          1512 non-null   object
 28  Order Description                   1512 non-null   object
 29  Resources                           1511 non-null   object
 30  FROM Batch                          1512 non-null   object
 31  TO Batch                            1512 non-null   object
 32  FROM Supply Level                   1510 non-null   object
 33  TO Supply Level                     1512 non-null   object
 34  FROM Proc Stage                     1510 non-null   object
 35  TO Proc Stage                       1512 non-null   object
 36  FROM Vendor Batch Number (LotNr)    1512 non-null   object
 37  TO Vendor Batch Number (LotNr)      1512 non-null   object
 38  Sani cd                             852 non-null    object
 39  Input TSW                           1505 non-null   object
 40  Output TSW                          1503 non-null   object
 41  Create Date                         1512 non-null   object
 42  GR date                             1512 non-null   object
 43  GI QTY                              1512 non-null   object
 44  GI UOM                              1508 non-null   object
 45  GR QTY                              1512 non-null   object
 46  GR UOM                              1512 non-null   object
 47  Blend/Split                         128 non-null    object
 48  Running Count of Batches            1512 non-null   object
 49  Unique Line for Input Analysis      1512 non-null   object
 50  Unique Line for Output Analysis     1512 non-null   object
 51  ABC                                 1512 non-null   object
 52  SG: % Normal seedlings - 1st count  5 non-null      object
 53  SG: % Normal seedlings -final       698 non-null    object
 54  UT - 1st choice                     1492 non-null   object
 55  UT - total                          1492 non-null   object
 56  UT: % Abnormals                     1492 non-null   object
 57  UT: % Ungerminated seeds            1492 non-null   object
 58  SG: % Normal seedlings -final       22 non-null     object
 59  UT - 1st choice                     239 non-null    object
 60  UT - total                          239 non-null    object
 61  UT: % Abnormals                     239 non-null    object
 62  UT: % Ungerminated seeds            239 non-null    object
 63  VR: Vigor Rating                    1512 non-null   object
 64  TT: % Normal seedlings 24C          1512 non-null   object
 65  TT: % Normal seedlings 28C          1512 non-null   object
 66  VR: Vigor Rating                    1512 non-null   object
 67  TT: % Normal seedlings 24C          1512 non-null   object
 68  TT: % Normal seedlings 28C          1512 non-null   object
dtypes: object(69)
memory usage: 826.9+ KB

In [23]:
df1

2,Priming Time (Hr),Supply Team,MG,MG Desc,MPG,MCT,SCO,Phase,Basic Material w/o Leading Zeros,Basic Variety Name,...,UT - 1st choice,UT - total,UT: % Abnormals,UT: % Ungerminated seeds,VR: Vigor Rating,TT: % Normal seedlings 24C,TT: % Normal seedlings 28C,VR: Vigor Rating,TT: % Normal seedlings 24C,TT: % Normal seedlings 28C
3,36,LEAFY,H187,LETTUCE,T4,BAV,OPN,5C,10822519,VENEGIA,...,NaN,NaN,NaN,NaN,10,100,42.5,0,100,99.5
4,28,LEAFY,H187,LETTUCE,T4,BUT,OPN,5C,10776016,TOUAREG,...,NaN,NaN,NaN,NaN,9.3125,90.5,74,0,100,100
5,24,LEAFY,H187,LETTUCE,T4,FRI,OPN,5C,10806290,FRILLICE,...,NaN,NaN,NaN,NaN,9.9375,100,74.5,0,100,99.5
6,36,LEAFY,H187,LETTUCE,T4,BUT,OPN,5C,10776016,TOUAREG,...,NaN,NaN,NaN,NaN,9.9375,94.5,13,0,100,97.5
7,36,LEAFY,H187,LETTUCE,T4,CRC,OPN,6D,10904727,PS 6545691,...,NaN,NaN,NaN,NaN,9.03125,0,0,0,100,99.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1510,48,LEAFY,H187,LETTUCE,T4,BAV,OPN,5C,10771677,SALAKIS,...,NaN,NaN,NaN,NaN,0,100,32,0,99,100
1511,48,LEAFY,H187,LETTUCE,T4,CHD,OPN,5B,10811570,MOHAWK,...,NaN,NaN,NaN,NaN,0,67,1.5,0,100,100
1512,48,LEAFY,H187,LETTUCE,T4,LOL,OPN,5C,10818377,XENON,...,NaN,NaN,NaN,NaN,0,97.5,55,0,100,99
1513,36,LEAFY,H187,LETTUCE,T4,FRI,OPN,5C,10806290,FRILLICE,...,NaN,NaN,NaN,NaN,0,98.5,18,0,100,99
1514,48,LEAFY,H187,LETTUCE,T4,BAV,OPN,5C,10759393,HUGIN,...,NaN,NaN,NaN,NaN,0,86,7.5,0,100,100

In [48]:
# Finding Duplicate column names
cols=pd.Series(df1.columns)
for index,dup in enumerate(cols.duplicated()):
    if dup:
        cols[index]=cols[index]+"-Primed"    

df1.columns = cols

In [49]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1512 entries, 3 to 1514
Data columns (total 69 columns):
 #   Column                                Non-Null Count  Dtype
---  ------                                --------------  -----
 0   Priming Time (Hr)                     1512 non-null   object
 1   Supply Team                           1512 non-null   object
 2   MG                                    1512 non-null   object
 3   MG Desc                               1512 non-null   object
 4   MPG                                   1512 non-null   object
 5   MCT                                   1512 non-null   object
 6   SCO                                   1511 non-null   object
 7   Phase                                 1512 non-null   object
 8   Basic Material w/o Leading Zeros      1512 non-null   object
 9   Basic Variety Name                    1512 non-null   object
 10  Material #                            1512 non-null   object
 11  Material Desc                         1512 non-null   object
 12  FROM Pack Type                        1512 non-null   object
 13  TO Pack Type                          1512 non-null   object
 14  FROM Prod Form                        1512 non-null   object
 15  TO Prod Form                          1512 non-null   object
 16  Proc Code                             1505 non-null   object
 17  Area                                  1502 non-null   object
 18  Harv Seq                              530 non-null    object
 19  Harv Date                             1512 non-null   object
 20  Crop Year                             1502 non-null   object
 21  Process Order                         1512 non-null   object
 22  FPO Plant                             1502 non-null   object
 23  OPO Plant                             1512 non-null   object
 24  Order Type                            1512 non-null   object
 25  Blend Indicator                       1512 non-null   object
 26  Scheduler Code                        1512 non-null   object
 27  Scheduler Code Description            1512 non-null   object
 28  Order Description                     1512 non-null   object
 29  Resources                             1511 non-null   object
 30  FROM Batch                            1512 non-null   object
 31  TO Batch                              1512 non-null   object
 32  FROM Supply Level                     1510 non-null   object
 33  TO Supply Level                       1512 non-null   object
 34  FROM Proc Stage                       1510 non-null   object
 35  TO Proc Stage                         1512 non-null   object
 36  FROM Vendor Batch Number (LotNr)      1512 non-null   object
 37  TO Vendor Batch Number (LotNr)        1512 non-null   object
 38  Sani cd                               852 non-null    object
 39  Input TSW                             1505 non-null   object
 40  Output TSW                            1503 non-null   object
 41  Create Date                           1512 non-null   object
 42  GR date                               1512 non-null   object
 43  GI QTY                                1512 non-null   object
 44  GI UOM                                1508 non-null   object
 45  GR QTY                                1512 non-null   object
 46  GR UOM                                1512 non-null   object
 47  Blend/Split                           128 non-null    object
 48  Running Count of Batches              1512 non-null   object
 49  Unique Line for Input Analysis        1512 non-null   object
 50  Unique Line for Output Analysis       1512 non-null   object
 51  ABC                                   1512 non-null   object
 52  SG: % Normal seedlings - 1st count    5 non-null      object
 53  SG: % Normal seedlings -final         698 non-null    object
 54  UT - 1st choice                       1492 non-null   object
 55  UT - total                            1492 non-null   object
 56  UT: % Abnormals                       1492 non-null   object
 57  UT: % Ungerminated seeds              1492 non-null   object
 58  SG: % Normal seedlings -final-Primed  22 non-null     object
 59  UT - 1st choice-Primed                239 non-null    object
 60  UT - total-Primed                     239 non-null    object
 61  UT: % Abnormals-Primed                239 non-null    object
 62  UT: % Ungerminated seeds-Primed       239 non-null    object
 63  VR: Vigor Rating                      1512 non-null   object
 64  TT: % Normal seedlings 24C            1512 non-null   object
 65  TT: % Normal seedlings 28C            1512 non-null   object
 66  VR: Vigor Rating-Primed               1512 non-null   object
 67  TT: % Normal seedlings 24C-Primed     1512 non-null   object
 68  TT: % Normal seedlings 28C-Primed     1512 non-null   object
dtypes: object(69)
memory usage: 826.9+ KB

In [53]:
df1.dtypes

2
Priming Time (Hr)                    object
Supply Team                          object
MG                                   object
MG Desc                              object
MPG                                  object
                                      ...
TT: % Normal seedlings 24C           object
TT: % Normal seedlings 28C           object
VR: Vigor Rating-Primed              object
TT: % Normal seedlings 24C-Primed    object
TT: % Normal seedlings 28C-Primed    object
Length: 69, dtype: object

In [50]:
report = sv.analyze(df1)

                                             |          | [  0%]   00:00 -> (? left)

In [51]:
report.show_html("./First view.html")

Report ./First view.html was generated! NOTEBOOK/COLAB USERS: the web browser MAY not pop up, regardless, the report IS saved in your notebook/colab files.

In [ ]:
report = sv.analyze(df1)

In [ ]:
# find delta of all changes
# use compare feature in sweetviz
# convert object to numbers